# ============================================================
# JAVA SPRING BOOT BACKEND
# ============================================================

# Define Spring Boot backend
upstream javaspringboot {
    server java_app:8080;
}


# ============================================================
# NGINX SERVER
# ============================================================

server {
    # Nginx listens on port 80
    listen 80;

    # Accept requests for any hostname or IP
    server_name _;


    # ========================================================
    # FORWARD REQUESTS TO SPRING BOOT
    # ========================================================

    location / {
        proxy_pass http://javaspringboot;

        # Forward request information
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
